basePath: /beta
definitions:
  ErrorResponse:
    properties:
      message:
        example: example error message
        type: string
      results:
        example: 0
        type: integer
      success:
        example: false
        type: boolean
    type: object
  GetPeakSyncedBlockResponse:
    properties:
      results:
        example: 1
        type: integer
      success:
        example: true
        type: boolean
      synced_block:
        $ref: '#/definitions/SyncedBlock'
    type: object
  GetPuzzleArgs:
    properties:
      puzzle_hash:
        example: 6b665c0e059050f71a1c3e8a7d5b58e4e1d7abbd02d937e9b5ab5abfd7f8eaba
        type: string
    type: object
  GetPuzzleResponse:
    properties:
      result:
        $ref: '#/definitions/Puzzle'
      results:
        example: 1
        type: integer
      success:
        example: true
        type: boolean
    type: object
  GetSingletonStatesArgs:
    properties:
      amount:
        example: 1
        format: int64
        type: integer
      coin_id:
        example: 625799464319c8703ac2d0664af98cf45b9b306f7dcf717b1070d170bb5916a9
        format: hex
        type: string
      header_hash:
        example: 796c33c3905150e649211fdd9ed42c7c418758c30c321271973a7c792a5bd403
        format: hex
        type: string
      height:
        example: 2174316
        format: int64
        type: integer
      inner_puzzle_hash:
        example: 6b665c0e059050f71a1c3e8a7d5b58e4e1d7abbd02d937e9b5ab5abfd7f8eaba
        format: hex
        type: string
      launcher_id:
        example: f4dd6f4ec490974f7eb98223748f47340a9e9363b4c2dccc1932cdbbc54d03fd
        format: hex
        type: string
      limit:
        example: 1337
        type: integer
      offset:
        example: 1
        type: integer
      order:
        example: desc
        type: string
      order_by:
        type: string
      parent_coin_id:
        example: e9676e8ce096c5be27dee2fbf2120054d206e4df2de9ef59c24a651d3c558c95
        format: hex
        type: string
      puzzle_hash:
        example: 0a5a9c760970ebcc094c6f9faa3d9730f066c7a8f7450841a94fc4fd59229bc2
        format: hex
        type: string
    type: object
  GetSingletonStatesResponse:
    properties:
      results:
        example: 1
        type: integer
      singleton_states:
        items:
          $ref: '#/definitions/SingletonState'
        type: array
      success:
        example: true
        type: boolean
    type: object
  GetSyncedBlockArgs:
    properties:
      height:
        example: 2000000
        type: integer
    type: object
  GetSyncedBlockResponse:
    properties:
      results:
        example: 1
        type: integer
      success:
        example: true
        type: boolean
      synced_block:
        $ref: '#/definitions/SyncedBlock'
    type: object
  GetSyncedBlocksArgs:
    properties:
      end:
        example: 2000001
        type: integer
      start:
        example: 2000000
        type: integer
    type: object
  GetSyncedBlocksResponse:
    properties:
      results:
        example: 1
        type: integer
      success:
        example: true
        type: boolean
      synced_blocks:
        items:
          $ref: '#/definitions/SyncedBlock'
        type: array
    type: object
  NoAPIKeyResponse:
    properties:
      message:
        example: No API key provided.
        type: string
      success:
        example: false
        type: boolean
    type: object
  Puzzle:
    properties:
      puzzle:
        example: ff02ffff01ff02ffff01ff02ff3effff04ff02ffff04ff05ffff04ffff02ff2fff5f80ffff04ff80ffff04ffff04ffff04ff0bffff04ff17ff808080ffff01ff808080ffff01ff8080808080808080ffff04ffff01ffffff0233ff04ff0101ffff02ff02ffff03ff05ffff01ff02ff1affff04ff02ffff04ff0dffff04ffff0bff12ffff0bff2cff1480ffff0bff12ffff0bff12ffff0bff2cff3c80ff0980ffff0bff12ff0bffff0bff2cff8080808080ff8080808080ffff010b80ff0180ffff0bff12ffff0bff2cff1080ffff0bff12ffff0bff12ffff0bff2cff3c80ff0580ffff0bff12ffff02ff1affff04ff02ffff04ff07ffff04ffff0bff2cff2c80ff8080808080ffff0bff2cff8080808080ffff02ffff03ffff07ff0580ffff01ff0bffff0102ffff02ff2effff04ff02ffff04ff09ff80808080ffff02ff2effff04ff02ffff04ff0dff8080808080ffff01ff0bffff0101ff058080ff0180ff02ffff03ff0bffff01ff02ffff03ffff09ff23ff1880ffff01ff02ffff03ffff18ff81b3ff2c80ffff01ff02ffff03ffff20ff1780ffff01ff02ff3effff04ff02ffff04ff05ffff04ff1bffff04ff33ffff04ff2fffff04ff5fff8080808080808080ffff01ff088080ff0180ffff01ff04ff13ffff02ff3effff04ff02ffff04ff05ffff04ff1bffff04ff17ffff04ff2fffff04ff5fff80808080808080808080ff0180ffff01ff02ffff03ffff09ff23ffff0181e880ffff01ff02ff3effff04ff02ffff04ff05ffff04ff1bffff04ff17ffff04ffff02ffff03ffff22ffff09ffff02ff2effff04ff02ffff04ff53ff80808080ff82014f80ffff20ff5f8080ffff01ff02ff53ffff04ff818fffff04ff82014fffff04ff81b3ff8080808080ffff01ff088080ff0180ffff04ff2cff8080808080808080ffff01ff04ff13ffff02ff3effff04ff02ffff04ff05ffff04ff1bffff04ff17ffff04ff2fffff04ff5fff80808080808080808080ff018080ff0180ffff01ff04ffff04ff18ffff04ffff02ff16ffff04ff02ffff04ff05ffff04ff27ffff04ffff0bff2cff82014f80ffff04ffff02ff2effff04ff02ffff04ff818fff80808080ffff04ffff0bff2cff0580ff8080808080808080ff378080ff81af8080ff0180ff018080ffff04ffff01a0a04d9f57764f54a43e4030befb4d80026e870519aaa66334aef8304f5d0393c2ffff04ffff01ffff75ffc05968747470733a2f2f6261666b726569657175656b6879786b34643575366e77653462733378366f6c7369616b646269753467353276736a7665666f6b78686f6d6b6d712e697066732e6e667473746f726167652e6c696e6b2f80ffff68a090a1147c5d5c1f69e6d89c0cb77f3972401430a29c37755926a42b9573b98a64ffff826d75ffc05968747470733a2f2f6261666b7265696468336273697933626835686870766e6d367572357176757474373566783277697772646f62736d70686e6c3237776f726372792e697066732e6e667473746f726167652e6c696e6b2f80ffff826c7580ffff82736e01ffff82737401ffff826d68a067d8648c6c27e9cefab59ea47b0ad273ff4b7d591688dc1931e76af5fb3a228e80ffff04ffff01a0fe8a4b4e27a2e29a4d3fc7ce9d527adbcaccbab6ada3903ccf3ba9a769d2d78bffff04ffff01ff02ffff01ff02ffff01ff02ffff03ff0bffff01ff02ffff03ffff09ff05ffff1dff0bffff1effff0bff0bffff02ff06ffff04ff02ffff04ff17ff8080808080808080ffff01ff02ff17ff2f80ffff01ff088080ff0180ffff01ff04ffff04ff04ffff04ff05ffff04ffff02ff06ffff04ff02ffff04ff17ff80808080ff80808080ffff02ff17ff2f808080ff0180ffff04ffff01ff32ff02ffff03ffff07ff0580ffff01ff0bffff0102ffff02ff06ffff04ff02ffff04ff09ff80808080ffff02ff06ffff04ff02ffff04ff0dff8080808080ffff01ff0bffff0101ff058080ff0180ff018080ffff04ffff01b093c8e9237b64d8e9282a7f8e73369c671bdf4e8fa631704c58ae8aa7a8912322994e22df1b01dd8c896e13cf1683ba2dff018080ff018080808080
        format: hex
        type: string
      puzzle_hash:
        example: 6b665c0e059050f71a1c3e8a7d5b58e4e1d7abbd02d937e9b5ab5abfd7f8eaba
        format: hex
        type: string
    type: object
  SingletonState:
    properties:
      amount:
        example: 1
        format: int64
        type: integer
      coin_id:
        example: 625799464319c8703ac2d0664af98cf45b9b306f7dcf717b1070d170bb5916a9
        format: hex
        type: string
      header_hash:
        example: 796c33c3905150e649211fdd9ed42c7c418758c30c321271973a7c792a5bd403
        format: hex
        type: string
      height:
        example: 2174316
        format: int64
        type: integer
      inner_puzzle_hash:
        example: 6b665c0e059050f71a1c3e8a7d5b58e4e1d7abbd02d937e9b5ab5abfd7f8eaba
        format: hex
        type: string
      launcher_id:
        example: f4dd6f4ec490974f7eb98223748f47340a9e9363b4c2dccc1932cdbbc54d03fd
        format: hex
        type: string
      melted:
        example: false
        type: boolean
      parent_coin_id:
        example: e9676e8ce096c5be27dee2fbf2120054d206e4df2de9ef59c24a651d3c558c95
        format: hex
        type: string
      puzzle_hash:
        example: 0a5a9c760970ebcc094c6f9faa3d9730f066c7a8f7450841a94fc4fd59229bc2
        format: hex
        type: string
    type: object
  SyncedBlock:
    properties:
      header_hash:
        example: 9bb7135ae2b4a207807be2661007a89c8e3d0de1a58c0670da07b6099b9fedf7
        format: hex
        type: string
      height:
        example: 2000000
        format: int64
        type: integer
    type: object
host: https://kraken.fireacademy.io
info:
  contact:
    email: y@kuhi.to
    name: yakuhito
    url: https://twitter.com/yakuh1t0
  description: The Beta FireAcademy.io API
  license:
    name: MIT
    url: https://github.com/FireAcademy/beta/blob/master/LICENSE
  termsOfService: https://fireacademy.io/terms-and-conditions.txt
  title: Beta API
  version: "1.0"
paths:
  /get_peak_synced_block:
    get:
      consumes:
      - application/json
      description: Beta constantly syncs to the blockchain by fetching the latest
        blocks. This function returns information about the latest processed block
        (the one with the biggest 'height' value).
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/GetPeakSyncedBlockResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/NoAPIKeyResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: returns the peak synced block
      tags:
      - Sync
    post:
      consumes:
      - application/json
      description: Beta constantly syncs to the blockchain by fetching the latest
        blocks. This function returns information about the latest processed block
        (the one with the biggest 'height' value).
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/GetPeakSyncedBlockResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/NoAPIKeyResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: returns the peak synced block
      tags:
      - Sync
  /get_puzzle:
    post:
      consumes:
      - application/json
      description: Beta stores all revealed inner puzzles of singletons. Use this
        method to get it from the corresponding puzzle hash. The puzzle will be returned
        as a hex string.
      parameters:
      - description: The inner puzzle hash
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/GetPuzzleArgs'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/GetPuzzleResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/NoAPIKeyResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: returns the stored puzzle for a given puzzle_hash
      tags:
      - Puzzle
  /get_singleton_states:
    post:
      consumes:
      - application/json
      description: |-
        Singletons are like souls - when a coin dies (gets spent), they might move on to a new coin or disappear (melt). Beta views these transitions as changes of state.
        This endpoint takes multiple optional arguments and returns the states that match the criteria. Most body parameters are self-explanatory: if they match a field of the returned struct model (e.g., 'height' or 'launcher_id'), they act as filters. Only states with the specified values will be returned.
        The first special parameter is 'limit' - by default, this function returns 100 results at most. Use this parameter to tweak this value.
        'order_by' can be 'coin_id', 'header_hash', 'height', 'parent_coin_id', 'puzzle_hash', 'amount', 'launcher_id', or 'inner_puzzle_hash'. The default ordering is ascending, but that can be changed by setting the 'order' parameter to 'desc'.
        If your query returns more than 100 results and you need all of them for some reasons, you can also use the 'offset' parameter.
        Note: Two singleton states CAN have the same coin id but a different 'melted' value - the primary key is a composite one: (coin_id, melted)
      parameters:
      - description: The arguments (see description for more details)
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/GetSingletonStatesArgs'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/GetSingletonStatesResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/NoAPIKeyResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: returns singleton states for given conditions
      tags:
      - Singleton States
  /get_synced_block:
    post:
      consumes:
      - application/json
      description: Beta constantly syncs to the blockchain by fetching the latest
        blocks. This function returns information about the block at the given height.
      parameters:
      - description: The height
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/GetSyncedBlockArgs'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/GetSyncedBlockResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/NoAPIKeyResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: returns block for given height
      tags:
      - Sync
  /get_synced_blocks:
    post:
      consumes:
      - application/json
      description: Beta constantly syncs to the blockchain by fetching the latest
        blocks. This function returns information about the blocks with height in
        [start, end).
      parameters:
      - description: The start and end heights
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/GetSyncedBlocksArgs'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/GetSyncedBlocksResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/NoAPIKeyResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: returns blocks for given range
      tags:
      - Sync
securityDefinitions:
  ApiKeyAuth:
    description: The API key can also be included in the URL or as a GET parameter
      - please see [https://docs.fireacademy.io/developers/using-api-keys](https://docs.fireacademy.io/developers/using-api-keys)
      for more details.
    in: header
    name: X-API-Key
    type: apiKey
swagger: "2.0"
